package ClavarChat.Models.Events.Enums;

public enum NETWORK_EVENT_TYPE
{
    NETWORK_EVENT_NEW_CONNECTION,
    NETWORK_EVENT_END_CONNECTION,
    NETWORK_EVENT_CONNECTION_SUCCESS,
    NETWORK_EVENT_DATA
}
